title: Ash Bellett

author:
  name:  Ash Bellett
  email: ash.bellett.ab@gmail.com

twitter_username:  ashbellett
github_username:   ashbellett
linkedin_username: ashbellett

include: [_pages]
baseurl: ""
url:     "ashbellett.com"

collections:
  set-theory:
    output: true
    permalink: /:collection/:path
    order:
      - logic.md
      - sets.md
      - functions.md
  real-analysis:
    output: true
    permalink: /:collection/:path
    order:
      - limits.md
      - derivatives.md
      - integrals.md
  linear-algebra:
    output: true
    permalink: /:collection/:path
    order:
      - vector-spaces.md
      - inner-product-spaces.md
      - matrices.md
      - determinants.md
      - eigenvalues-eigenvectors.md
      - singular-value-decomposition.md

social:
  - { platform: github }
  - { platform: linkedin }
  - { platform: twitter }
  - { platform: youtube }

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
