title: Ash Bellett
author:
  name: Ash Bellett
  email: ash.bellett.ab@gmail.com
include: [_pages]
collections_dir: _posts
baseurl: ""
url: "ashbellett.com"
collections:
  sets:
    key: 0
    title: "Sets"
    description: "Collections of objects"
    output: true
    permalink: /:collection/:path
    order:
      - logic.md
      - sets.md
      - functions.md
  real-analysis:
    key: 1
    title: "Real Analysis"
    description: "Real-valued numbers and functions"
    output: true
    permalink: /:collection/:path
    order:
      - real-numbers.md
      - sequences.md
      - limits.md
      - series.md
      - continuity.md
      - derivatives.md
      - integrals.md
  linear-algebra:
    key: 2
    title: "Linear Algebra"
    description: "Representations of linear systems"
    output: true
    permalink: /:collection/:path
    order:
      - vector-spaces.md
      - inner-product-spaces.md
      - matrices.md
      - determinants.md
      - eigenvalues-eigenvectors.md
      - matrix-decompositions.md
      - linear-transformations.md
  probability:
    key: 3
    title: "Probability"
    description: "Occurrences of uncertain events"
    output: true
    permalink: /:collection/:path
    order:
      - events.md
      - probability-spaces.md
      - conditional-probability.md
      - random-variables.md
      - distributions.md
      - moments.md
      - limit-theorems.md
      - concentration-bounds.md
      - probabilistic-convergence.md
      - stochastic-processes.md
  frequentist-statistics:
    key: 4
    title: "Frequentist Statistics"
    description: "Drawing conclusions from data"
    output: true
    permalink: /:collection/:path
    order:
      - samples.md
      - sufficiency.md
      - estimators.md
      - point-estimation.md
      - interval-estimation.md
      - hypothesis-testing.md
  bayesian-statistics:
    key: 5
    title: "Bayesian Statistics"
    description: "Modelling parameters as random variables"
    output: true
    permalink: /:collection/:path
  optimisation:
    key: 6
    title: "Optimisation"
    description: "Maximising and minimising functions"
    output: true
    permalink: /:collection/:path
    order:
      - convexity.md
      - unconstrained-optimisation.md
      - constrained-optimisation.md
socials:
  - {
    platform: github,
    username: ashbellett,
    url: github.com/ashbellett
  }
  - {
    platform: linkedin,
    username: ashbellett,
    url: linkedin.com/in/ashbellett
  }
analytics: G-XFWQPSWM13
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
