title: Ash Bellett

author:
  name:  Ash Bellett
  email: ash.bellett.ab@gmail.com

include: [_pages]
collections_dir: _posts
baseurl: ""
url:     "ashbellett.com"

collections:
  sets:
    output: true
    permalink: /:collection/:path
    order:
      - logic.md
      - sets.md
      - functions.md
  analysis:
    output: true
    permalink: /:collection/:path
    order:
      - real-numbers.md
      - sequences.md
      - limits.md
      - series.md
      - continuity.md
      - derivatives.md
      - integrals.md
  algebra:
    output: true
    permalink: /:collection/:path
    order:
      - vector-spaces.md
      - linear-transformations.md
      - inner-product-spaces.md
      - matrices.md
      - determinants.md
      - eigenvalues-eigenvectors.md
      - matrix-decompositions.md
  probability:
    output: true
    permalink: /:collection/:path
    order:
      - probability-spaces.md
      - probability-forms.md
      - random-variables.md
      - distributions.md
      - moments.md
      - limit-theorems.md
      - concentration-bounds.md
      - probabilistic-convergence.md
      - stochastic-processes.md
  statistics:
    output: true
    permalink: /:collection/:path
    order:
      - samples.md
      - estimators.md
      - point-estimation.md
      - interval-estimation.md
      - hypothesis-testing.md
  optimisation:
    output: true
    permalink: /:collection/:path
    order:
      - convexity.md
      - unconstrained-optimisation.md
      - constrained-optimisation.md

socials:
  - {
    platform: github,
    username: ashbellett,
    url: github.com/ashbellett
  }
  - {
    platform: linkedin,
    username: ashbellett,
    url: linkedin.com/in/ashbellett
  }
  - {
    platform: twitter,
    username: ashbellett,
    url: twitter.com/ashbellett
  }

analytics: G-XFWQPSWM13

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
