title:  Ash Bellett
author: Ash Bellett
email:  ash.bellett.ab@gmail.com

twitter_username:   ashbellett
github_username:    ashbellett
linkedin_username:  ashbellett

baseurl:  ""
url:      "ashbellett.com"

theme:  minima

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
