title: Ash Bellett

author:
  name:  Ash Bellett
  email: ash.bellett.ab@gmail.com

include: [_pages]
baseurl: ""
url:     "ashbellett.com"

collections:
  set-theory:
    output: true
    permalink: /:collection/:path
    order:
      - logic.md
      - sets.md
      - functions.md
  real-analysis:
    output: true
    permalink: /:collection/:path
    order:
      - limits.md
      - derivatives.md
      - integrals.md
  linear-algebra:
    output: true
    permalink: /:collection/:path
    order:
      - vector-spaces.md
      - linear-transformations.md
      - inner-product-spaces.md
      - matrices.md
      - determinants.md
      - eigenvalues-eigenvectors.md
      - matrix-decompositions.md
  probability-theory:
    output: true
    permalink: /:collection/:path
  statistics:
    output: true
    permalink: /:collection/:path
  optimisation:
    output: true
    permalink: /:collection/:path

socials:
  - {
    platform: github,
    username: ashbellett,
    url: github.com/ashbellett
  }
  - {
    platform: linkedin,
    username: ashbellett,
    url: linkedin.com/in/ashbellett
  }
  - {
    platform: twitter,
    username: ashbellett,
    url: twitter.com/ashbellett
  }

analytics: G-XFWQPSWM13

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
